project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Stochastic Processes"
  author: "Thiyanga S. Talagala"
  date: "28/10/2023"
  reader-mode: true
  page-footer:
    left: |
      Introduction to Stochastic Processes (1e) was written by Thiyanga S. Talagala.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/thiyangt/tst.stochasticprocesses
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



