# Birth Process, Death Process and Birth-Death Process.

- A birth-death process is a continuous-time Markov chain used to describe the evolution of the system by counting the number of individuals in the system over time. 

- In this dynamic system, each individual has the potential to either give birth to a new individual or undergo a death event. 

- The rates of these birth and death events at any given time depends upon the current number of existing individuals in the system.

## Applications of Birth-Death Process

- Genetics, epidemiology: Study of infectious diseases, birth-death processes can be employed to model the spread of infections within a population

- Ecology:  model the birth and death rates of different species in a habitat

- Epidemiology: model number of infected individuals 

## Definition: Transition Probability

<!--https://www.sciencedirect.com/science/article/pii/S0895717711005541-->

Let $N(t)$ be the number of individuals at arbitrary time $t$ for $t \geq 0$ and $\{N(t): t \geq 0\}$ be the sequence of random variables which define a birth-death Markov chain with a birth rate $\lambda_i$ and death rate $\mu_i$ for state $i$. Assume that an arbitrary community with $r$ individuals, thus $N(0) = r$ for some $r > 0$.


The stationary transition probability is defined as follows:

$$P_{ij}(t) = P\{N(s+t) = j|N(s) = i\} \text{ for all } s \text{and } t>0$$

## Instantaneous birth rate and instantaneous death rate

Consider a population of $N(t)$ individuals. Suppose in next time interval $(t, t+h)$ probability of population increase of 1 (called a birth) is $\lambda_ih + o(h)$ and probability of decrease of 1 (death) is $\mu_ih + o(h)$. Here $\lambda_i$ is called the instantaneous birth rate and $\mu_i$ is called instantaneous death rate.

Further, we have

$$
    q_{ij}= 
\begin{cases}
    0,& \text{if } |i-j|\geq 1\\
    \lambda_i, & \text{if } j=i+1\\
    \mu_{i},              & \text{if } j=i-1
\end{cases}
$$


## Postulates

Let $$P_{ij}(h) = P(N(t+h) = j|N(t) = i)\text{ for all }t \geq 0,$$

Further, $P_{ij}(t)$ satisfy,

1. $P_{i, i+1}(h) = P(N(t+h) = i+1|N(t)=i) = \lambda_ih + o(h), i \geq 0$

2. $P_{i, i-1}(h)=P(N(t+h) = i-1|N(t)=i) = \mu_ih + o(h), i \geq 1$

3. $P_{i, i}(h)= P(N(t+h) = i|N(t)=i) = 1- (\lambda_i + \mu_i)h + o(h), i \geq 0$

4. $P(N(t+h) = i+m|N(t)=i) = o(h), |m| > 1$

5. $\mu_0 = 0, \lambda_0 > 0, \mu_i, \lambda_i > 0, i=1, 2, 3,,,,$

## Exercise 

Show that the birth process, death process and birth-death process  are  Markov processes

## Special cases

1. When all $\mu_i = 0$, called a pure birth process.

2. When all $\lambda_i = 0$ called a pure death process

3. When $\lambda_n = n\lambda$ and $\mu_n = n\lambda$ is a linear birth and death process.

4. When $\lambda_n = \lambda$ and $\mu_n = 0$ is called a Poisson process.

## Exercise

Derive the distribution of length of stay (elapsed time between two consecutive occurrences ) for a birth, death and birth-death process.
