# Introduction

## What is a Stochastic Process?

First, let's see what does "stochastic" mean?  The meaning of "stochastic" is **random**.  The term "process" refers to a mathematical or statistical model that describes the evolution of a random variable over time. In the study of a stochastic process, we examine a collection of random variables indexed by a certain parameter, typically time, representing the evolution of a system over a series of discrete or continuous instances.

For example, suppose we monitor the weather condition every hour in a day sunny, rainy, and cloudy. Then you are essentially observing a stochastic process. This process describes how the weather condition evolves over time.  


Can we describe this situation using a single random variable? No, we cannot. We need a sequence of random variables index by time as follows:

$X_0$ - weather condition from 00:00 to 01:00

$X_1$ - weather condition from 01:00 to 02:00

.

.

.

$X_{23}$ - weather condition from 23:00 - 00:00




The above scenario can be framed as a stochastic process. Here's how it relates to the concept of a stochastic process:

**Time index:** The time index is the hour of the day as 0, 1, 2, 3, ... 23. Each hour is a specific point in time.

**Random variable:** The weather conditions at each hour can be viewed as random variables. These random variables can be take different values such as sunny, rainy and cloudy. The weather conditions sunny,rainy and cloudy are called *states* (see Section for more information).


In many real life situations, observations are made over a period of time. Stochastic processes are used to model and analyze such time-dependent random phenomena, allowing you to study the probabilistic behavior and make predictions about future states based on past observations. When dealing with stochastic processes, we can address various probabilistic questions, including but not limited to:

1. **Conditional probabilities: **For instance, given that the weather has been cloudy for the first five hours of the day, you can use the stochastic process to estimate the likelihood of it remaining cloudy or changing to a different condition in the next hour.

2. **Time to an event: ** For example, you can estimate how long it will take for the weather to change from cloudy to sunny.

3. **Transition probabilities: ** For instance, you can determine the likelihood of going from a rainy day to a sunny day or vice versa.

4. **Frequency of Events:** You can examine the frequency of specific events occurring within a given time frame.

These are just a few examples of the probabilistic questions that can be addressed using stochastic processes. The specific questions you can answer will depend on the nature of the process and the data available for analysis.

## Definition of a stochastic process

**Definition 1**

A stochastic process is a collection of random variables $\{X_t, t\in T\}$ or ${X(t), t \in T}$ where $T$ is an index set.That is for each $t \in T$, the random variable $X_t$ (or $X(t)$) is a random variable.

## Parameter space

In definition 1, the index set $T$ is called the parameter space. It is usually interpreted as a time variable,telling us when the process is measured. The parameter space can be discrete or continuous. 

### Discrete-parameter process

When $T$ is a countable set, the process is said to be a discrete-parameter process. A discrete-parameter stochastic process is defined as follows:

$$\{X_t: t \in T\}$$
**Example:** Number of Customers Arriving Each Hour to a particular super market (Discrete Parameter Space)

In this scenario, you are interested in the number of customers arriving during each discrete time interval, typically on an hourly basis. 

### Continuous-parameter space

When $T$ is an interval of the real line, the process is said to be a continuous-parameter process. A continuous-parameter stochastic process is defined as follows:

$$\{X(t): t \in T\}$$

**Example 1:** Number of Customers Arriving from 8 AM to 10 PM (Continuous Parameter Space): 

In this scenario, you are interested in the total number of customers arriving over a continuous time period, specifically from 8 AM to 10 PM.

## State space

The set of possible values of an individual random variable $X_t$ or $X(t)$ of a stochastic process is called the state space. The state space can be discrete or continuous.

## Random Variable in Probability Theory vs Stochastic Theory

### Probability theory

<!--All very important.-->

Let $(\Omega, \mathscr{F}, \mathbb{P})$ be a probability space. A measurable mapping $X: \Omega \rightarrow \mathbb{R}$ is called a random variable. The $X(\omega)$ for $\omega \in \Omega$ iscalled a realization of $X$.

**Example:**


### Stochastic theory

Suppose that $(\Omega, \mathscr{F}, \mathbb{P})$ is a probability space, the function $X: T \times \Omega \rightarrow \mathbb{R}$ .

- We will always assume that the cardinality of $T$ is infinite, either countable or
uncountable.

If $T=\mathbb{Z}^+$ then we called X a discrete time stochastic process.

If $I = [0,\infty)$,
then $X$ is said to be a continuous time stochastic processes.

## Sample path (trajectory) of a stochastic process

The function $t \rightarrow X_t(\omega)$ ($t \rightarrow X(t)(\omega)$) is called a sample path of the stochastic process. For each 
  
**Example:**

## Types of Stochastic Processes

Depending on the parameter space and state space we can define four type of stochastic processes.

**1. Discrete-Parameter Discrete-State Space Stochastic Processes:**

  - Parameter Space: Discrete
 
  - State Space: Discrete

  - Examples: Assessment of crop condition during routine field inspections in agriculture is categorized as: healthy, pest-infested, diseased, damaged. These field inspections are typically conducted at regular intervals, such as once a week
  
**2. Continuous-Parameter Discrete-State Space Stochastic Processes:**

  - Parameter Space: Continuous
 
  - State Space: Discrete

  - Examples: 

**3. Discrete-Parameter Continous-State Space Stochastic Processes:**

  - Parameter Space: Discrete
 
  - State Space: Continuous

  - Examples: 

**4. Continuous-Parameter Continuous-State Space Stochastic Processes:**

  - Parameter Space: Continuous
 
  - State Space: Continuous

  - Examples: 
  
## Stationary condition of a stochastic process
 
 

## Independent increments condition of a stochastic process

## Stationary increments condition of a stochastic process

## Stochastic process vs a deterministic process   

## Stochastic proceses vs Time series

Realization

multiple realizations of a stochastic process.

## Stochastic processes vs probaility calculation in a single random variable

## Applications of stochastic processes

